name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: crud-nestjs
  NODE_VERSION: "18.x"
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      #Criação do ambiente de teste
      - name: Obter o código do repositório
        uses: actions/checkout@v3.5.2
      - name: Setup ambiente node
        uses: actions/setup-node@v2.5.2
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Executando um teste (quando houver)
        run: |
          npm install
          npm run test
        working-directory: ./

      #Login no docker hub
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          path: ./Dockerfile
          push: true
          tags: |
            biel2802/crud-nestjs:latest
            biel2802/crud-nestjs:v${{ github.run_number }}
